#specific_graphs:
#  - path: /home/maciej/Documents/mgr/praca_mgr/data/terrorist/standard/madrid.anet
#  - path: /home/maciej/Documents/mgr/praca_mgr/data/terrorist/standard/bali.anet
#  - path: /home/maciej/Documents/mgr/praca_mgr/data/terrorist/standard/wtc.anet

random_graphs:
  - func: 'random_graphs.small_world_network'
    nodes: 100
    average_degree: 10
    rewiring_probability: 0.25
    samples: 50
#  - func: 'random_graphs.scale_free_network'
#    nodes: 100
#    links: 3
#    samples: 50
#  - func: 'random_graphs.Erdos_Renyi_graph'
#    nodes: 100
#    average_degree: 10
#    samples: 50

cutting_graph_heuristics:
  - func: 'heuristics.diode'
    label: 'diode'
    budgets: [1, 2, 3, 4]
    executions: 4
#  - func: 'heuristics.remove_one_add_many'
#    label: 'roam'
#    budgets: [1, 2, 3, 4]
#    executions: 8

include_metrics:
#  - name: 'metrics.EffectivenessMetric'
  - name: 'metrics.EffectivenessMetric'
    step_numbers: 2
  - name: 'metrics.EffectivenessMetric'
    step_numbers: 3
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.KCoreDecompositionMetric'
    iterations: 1
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.NeighborhoodCorenessMetric'
    iterations: 1
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.DegreeMetric'
    iterations: 1

influences:
  add_plots: True
  sample_size: 200
  dummy_alpha: 0.8
