specific_graphs:
  - path: bali.anet

#random_graphs:
#  - func: 'random_graphs.small_world_network'
#    nodes: 100
#    average_degree: 10
#    rewiring_probability: 0.25
#    samples: 2
#  - func: 'random_graphs.scale_free_network'
#    nodes: 100
#    links: 3
#    samples: 50
#  - func: 'random_graphs.Erdos_Renyi_graph'
#    nodes: 100
#    average_degree: 10
#    samples: 50

cutting_graph_heuristics:
  - func: 'heuristics.diode'
    label: 'DIODE'
    budgets: [1]
    executions: 2
#  - func: 'heuristics.remove_one_add_many'
#    label: 'roam'
#    budgets: [1, 2, 3, 4]
#    executions: 8

exclude_metrics:
  - name: 'metrics.EffectivenessMetric'
  - name: 'metrics.DegreeMetric'
#    step_numbers: 2

influences:
  add_plots: False
  sample_size: 20000
  dummy_alpha: 0.25
