specific_graphs:
  - path: /home/maciej/Documents/mgr/praca_mgr/data/terrorist/standard/madrid.anet

#random_graphs:
#  - func: 'random_graphs.small_world_network'
#    nodes: 100
#    average_degree: 10
#    rewiring_probability: 0.25
#    samples: 50

cutting_graph_heuristics:
#  - func: 'modify_graph.remove_one_better_bot_enters'
#    label: 'robe'
#    budgets: [1]
#    executions: 10
  - func: 'heuristics.remove_one_add_many'
    label: 'roam'
    budgets: [1]
    executions: 4

include_metrics:
  - name: 'metrics.EffectivenessMetric'
  - name: 'metrics.EffectivenessMetric'
    step_numbers: 2
  - name: 'metrics.EffectivenessMetric'
    step_numbers: 3
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.KCoreDecompositionMetric'
    iterations: 1
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.NeighborhoodCorenessMetric'
    iterations: 1
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.DegreeMetric'
    iterations: 1

influences:
  add_plots: False
  sample_size: 1000
