specific_graphs:
  - path: /home/dom/important/data/terrorist/standard/madrid.anet

random_graphs:
  probes: 1000
  nodes_number_range: "100-1000"
  edges_per_node_avg: 10

cutting_graph_heuristic: 'graphs.remove_one_bot_enters'

append_influences_plot: True

label: 'robe'
