# specific_graphs:
#   - path: /home/dom/important/data/terrorist/standard/madrid.anet

random_graphs:
  - func: 'random_graphs.scale_free_network'
    nodes: 20
    links: 3
    samples: 30

cutting_graph_heuristics:
  - func: 'graphs.remove_one_bot_enters'
    label: 'robe'
  - func: 'graphs.remove_one_add_many'
    label: 'roam'
  - func: 'graphs.add_bot_assistant'
    label: 'aba'

include_metrics:
  - name: 'metrics.EffectivenessMetric'
  - name: 'metrics.EffectivenessMetric'
    step_numbers: 2
  - name: 'metrics.EffectivenessMetric'
    step_numbers: 3
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.KCoreDecompositionMetric'
    iterations: 1
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.NeighborhoodCorenessMetric'
    iterations: 1
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.DegreeMetric'
    iterations: 1

append_influences_plot: True
