# specific_graphs:
#   - path: /home/dom/important/data/terrorist/standard/madrid.anet

random_graphs:
  - func: 'random_graphs.scale_free_network'
    nodes: 20
    links: 3
    samples: 30

cutting_graph_heuristics:
  - func: 'modify_graph.remove_one_better_bot_enters'
    label: 'robe'
    budgets: [1]
  - func: 'modify_graph.remove_one_add_many'
    label: 'roam'
    budgets: [1, 2, 3, 4]

include_metrics:
  - name: 'metrics.EffectivenessMetric'
  - name: 'metrics.EffectivenessMetric'
    step_numbers: 2
  - name: 'metrics.EffectivenessMetric'
    step_numbers: 3
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.KCoreDecompositionMetric'
    iterations: 1
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.NeighborhoodCorenessMetric'
    iterations: 1
  - name: 'metrics.INGScoreMetric'
    benchmark_centrality: 'metrics.DegreeMetric'
    iterations: 1

append_influences_plot: True
